"""
Report exporters: Markdown and PDF (ReportLab).
Updated to support: executive_summary, challenge impact, opportunity priority,
structured sources (url+title+type), and leadership source_url.
"""

from io import BytesIO
from datetime import datetime
from typing import Dict

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, ListFlowable, ListItem, HRFlowable,
)


# ─────────────────────────────────────────────────────────────────────────────
# Markdown export
# ─────────────────────────────────────────────────────────────────────────────
def to_markdown(report: Dict) -> str:
    company = report["company"]
    a = report.get("analyst", {})
    s = report.get("strategy", {})
    pitch = report.get("pitch", "")
    exec_summary = report.get("executive_summary", "")

    ov = a.get("overview", {})
    kb = a.get("key_business_info", {})
    leaders = a.get("leadership", [])
    sources = a.get("sources", [])

    def bullets(items):
        return "\n".join(f"- {x}" for x in (items or [])) or "- _Not publicly disclosed_"

    md = f"""# 📊 AI-Powered Intelligence Report: {company}

> _Generated on {datetime.now().strftime("%B %d, %Y at %H:%M")}_

---

## 0. Executive Summary

{exec_summary or "_Executive summary not available._"}

---

## 1. Company Overview

| Field | Value |
|---|---|
| **What they do** | {ov.get('what_they_do', 'N/A')} |
| **Industry** | {ov.get('industry', 'N/A')} |
| **Scale** | {ov.get('scale', 'N/A')} |
| **Geographic Presence** | {ov.get('geographic_presence', 'N/A')} |
| **Founded** | {ov.get('founded', 'N/A')} |
| **Headquarters** | {ov.get('headquarters', 'N/A')} |
| **Website** | {ov.get('website', 'N/A')} |

---

## 2. Leadership Team

"""
    if leaders:
        for p in leaders:
            src = p.get("source_url", "")
            src_md = f"  \n  📎 [Source]({src})" if src else ""
            md += f"### 👤 {p.get('name', 'Unknown')}\n"
            md += f"**Role:** {p.get('role', 'N/A')}{src_md}\n\n"
            md += f"{p.get('bio', '')}\n\n"
    else:
        md += "_No leadership information was found in public sources._\n\n"

    md += f"""---

## 3. Key Business Information

### Major Offerings
{bullets(kb.get('major_offerings'))}

### Recent Developments
{bullets(kb.get('recent_developments'))}

### Expansion Plans
{bullets(kb.get('expansion_plans'))}

### Notable Public Information
{bullets(kb.get('notable_public_info'))}

---

## 4. Potential Business Challenges

"""
    for i, c in enumerate(s.get("challenges", []), 1):
        impact = c.get("impact", "")
        impact_md = f"\n> 📊 **Business Impact:** {impact}" if impact else ""
        md += f"### {i}. {c.get('title', 'Untitled')}  \n"
        md += f"_Category: **{c.get('category', 'N/A')}**_\n\n"
        md += f"{c.get('description', '')}\n\n"
        md += f"> **Reasoning:** {c.get('reasoning', '')}\n"
        md += f"{impact_md}\n\n"

    md += "---\n\n## 5. AI Opportunities\n\n"
    for i, o in enumerate(s.get("ai_opportunities", []), 1):
        prio = o.get("priority", "Medium")
        prio_icon = {"High": "🔴", "Medium": "🟡", "Low": "🔵"}.get(prio, "🔵")
        impl = o.get("implementation_idea", o.get("solution", ""))
        impact = o.get("expected_business_impact", o.get("expected_impact", ""))
        prio_reason = o.get("priority_reasoning", "")
        md += f"### 💡 {i}. {o.get('title', 'Untitled')} · {prio_icon} Priority: {prio}\n"
        md += f"- **Problem Solved:** {o.get('problem_solved', '')}\n"
        md += f"- **Implementation Idea:** {impl}\n"
        md += f"- **Expected Business Impact:** {impact}\n"
        md += f"- **Tech Stack:** `{o.get('tech_stack', '')}`\n"
        if prio_reason:
            md += f"- **Priority Reasoning:** _{prio_reason}_\n"
        md += "\n"

    md += f"---\n\n## 6. Personalized Pitch to the CEO\n\n{pitch}\n\n---\n\n## 7. Research Sources\n\n"
    if sources:
        from collections import defaultdict
        by_type = defaultdict(list)
        for src in sources:
            by_type[src.get("type", "Other")].append(src)
        for t, srcs in by_type.items():
            md += f"### {t}\n"
            for src in srcs:
                title = src.get("title", src.get("url", ""))
                url = src.get("url", "")
                md += f"- [{title}]({url})\n"
            md += "\n"
    else:
        md += "_No URLs captured._\n"

    md += "\n---\n\n_Report generated by the AI Research & Recommendation Agent_\n"
    return md


# ─────────────────────────────────────────────────────────────────────────────
# PDF export
# ─────────────────────────────────────────────────────────────────────────────
def _styles():
    base = getSampleStyleSheet()
    s = {}
    s["title"] = ParagraphStyle("Title", parent=base["Title"],
                                fontSize=24, leading=28, textColor=colors.HexColor("#7c3aed"), spaceAfter=4)
    s["subtitle"] = ParagraphStyle("Sub", parent=base["Normal"],
                                   fontSize=10, textColor=colors.HexColor("#6b7280"), spaceAfter=16)
    s["h1"] = ParagraphStyle("H1", parent=base["Heading1"],
                             fontSize=16, leading=20, textColor=colors.HexColor("#111827"),
                             spaceBefore=14, spaceAfter=8)
    s["h2"] = ParagraphStyle("H2", parent=base["Heading2"],
                             fontSize=12.5, leading=16, textColor=colors.HexColor("#7c3aed"),
                             spaceBefore=10, spaceAfter=6)
    s["h3"] = ParagraphStyle("H3", parent=base["Heading3"],
                             fontSize=11, leading=14, textColor=colors.HexColor("#1f2937"),
                             spaceBefore=8, spaceAfter=4)
    s["body"] = ParagraphStyle("Body", parent=base["BodyText"],
                               fontSize=10, leading=14, textColor=colors.HexColor("#1f2937"), spaceAfter=6)
    s["quote"] = ParagraphStyle("Quote", parent=s["body"],
                                leftIndent=12, textColor=colors.HexColor("#4b5563"),
                                fontName="Helvetica-Oblique", spaceAfter=8)
    s["impact"] = ParagraphStyle("Impact", parent=s["body"],
                                 leftIndent=12, textColor=colors.HexColor("#92400e"),
                                 fontName="Helvetica-Oblique", spaceAfter=8,
                                 backColor=colors.HexColor("#fef3c7"))
    s["label"] = ParagraphStyle("Label", parent=s["body"],
                                fontName="Helvetica-Bold", textColor=colors.HexColor("#7c3aed"))
    s["exec"] = ParagraphStyle("Exec", parent=s["body"],
                               fontSize=11, leading=16, textColor=colors.HexColor("#1e3a5f"),
                               spaceBefore=4, spaceAfter=8)
    return s


def _hr():
    return HRFlowable(width="100%", thickness=0.6,
                      color=colors.HexColor("#e5e7eb"), spaceBefore=6, spaceAfter=10)


def _bullets_pdf(items, style):
    if not items:
        return Paragraph("<i>Not publicly disclosed.</i>", style)
    return ListFlowable(
        [ListItem(Paragraph(str(x), style), leftIndent=8) for x in items],
        bulletType="bullet", start="•", leftIndent=14,
    )


def _esc(text: str) -> str:
    if text is None:
        return ""
    return (str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def to_pdf(report: Dict) -> bytes:
    company = report["company"]
    a = report.get("analyst", {})
    s = report.get("strategy", {})
    pitch = report.get("pitch", "")
    exec_summary = report.get("executive_summary", "")
    ov = a.get("overview", {})
    kb = a.get("key_business_info", {})
    leaders = a.get("leadership", [])
    sources = a.get("sources", [])

    st = _styles()
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=1.8*cm, bottomMargin=1.8*cm,
                            title=f"{company} – AI Intelligence Report")
    story = []

    # Cover
    story.append(Paragraph("AI-Powered Intelligence Report", st["title"]))
    story.append(Paragraph(
        f"<b>{_esc(company)}</b> &nbsp;·&nbsp; Generated {datetime.now().strftime('%B %d, %Y')}",
        st["subtitle"]))
    story.append(_hr())

    # 0. Executive Summary
    if exec_summary:
        story.append(Paragraph("Executive Summary", st["h1"]))
        for para in exec_summary.split("\n\n"):
            para = para.strip()
            if para:
                story.append(Paragraph(_esc(para), st["exec"]))
        story.append(_hr())

    # 1. Overview
    story.append(Paragraph("1. Company Overview", st["h1"]))
    rows = [
        ["What they do", ov.get("what_they_do", "N/A")],
        ["Industry", ov.get("industry", "N/A")],
        ["Scale", ov.get("scale", "N/A")],
        ["Geographic Presence", ov.get("geographic_presence", "N/A")],
        ["Founded", ov.get("founded", "N/A")],
        ["Headquarters", ov.get("headquarters", "N/A")],
        ["Website", ov.get("website", "N/A")],
    ]
    tbl = Table(
        [[Paragraph(f"<b>{_esc(k)}</b>", st["body"]),
          Paragraph(_esc(v), st["body"])] for k, v in rows],
        colWidths=[4.2*cm, 12*cm],
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#f5f3ff")),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("BOX", (0,0), (-1,-1), 0.4, colors.HexColor("#e5e7eb")),
        ("INNERGRID", (0,0), (-1,-1), 0.3, colors.HexColor("#e5e7eb")),
        ("LEFTPADDING", (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 6),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
    ]))
    story.append(tbl)

    # 2. Leadership
    story.append(Paragraph("2. Leadership Team", st["h1"]))
    if leaders:
        for p in leaders:
            src = p.get("source_url", "")
            src_txt = f" | Source: {src}" if src else ""
            story.append(Paragraph(
                f"👤 <b>{_esc(p.get('name','Unknown'))}</b> &nbsp;—&nbsp; <i>{_esc(p.get('role','N/A'))}</i>{_esc(src_txt)}",
                st["h3"]))
            if p.get("bio"):
                story.append(Paragraph(_esc(p.get("bio")), st["body"]))
    else:
        story.append(Paragraph("<i>No leadership information was found in public sources.</i>", st["body"]))

    # 3. Key Business Info
    story.append(Paragraph("3. Key Business Information", st["h1"]))
    for label, key in [("Major Offerings", "major_offerings"),
                       ("Recent Developments", "recent_developments"),
                       ("Expansion Plans", "expansion_plans"),
                       ("Notable Public Information", "notable_public_info")]:
        story.append(Paragraph(label, st["h2"]))
        story.append(_bullets_pdf([_esc(x) for x in kb.get(key, [])], st["body"]))
        story.append(Spacer(1, 4))

    # 4. Challenges
    story.append(PageBreak())
    story.append(Paragraph("4. Potential Business Challenges", st["h1"]))
    for i, c in enumerate(s.get("challenges", []), 1):
        story.append(Paragraph(
            f"{i}. {_esc(c.get('title','Untitled'))} <font color='#9ca3af'>· {_esc(c.get('category',''))}</font>",
            st["h2"]))
        story.append(Paragraph(_esc(c.get("description","")), st["body"]))
        if c.get("reasoning"):
            story.append(Paragraph(f"<b>Reasoning:</b> {_esc(c.get('reasoning'))}", st["quote"]))
        if c.get("impact"):
            story.append(Paragraph(f"<b>Business Impact:</b> {_esc(c.get('impact'))}", st["impact"]))

    # 5. AI Opportunities
    story.append(Paragraph("5. AI Opportunities", st["h1"]))
    for i, o in enumerate(s.get("ai_opportunities", []), 1):
        prio = o.get("priority", "Medium")
        prio_icon = {"High": "🔴", "Medium": "🟡", "Low": "🔵"}.get(prio, "🔵")
        impl = o.get("implementation_idea", o.get("solution", ""))
        impact = o.get("expected_business_impact", o.get("expected_impact", ""))
        story.append(Paragraph(f"💡 {i}. {_esc(o.get('title','Untitled'))} · {prio_icon} {prio} Priority", st["h2"]))
        story.append(Paragraph(f"<b>Problem Solved:</b> {_esc(o.get('problem_solved',''))}", st["body"]))
        story.append(Paragraph(f"<b>Implementation Idea:</b> {_esc(impl)}", st["body"]))
        story.append(Paragraph(f"<b>Expected Business Impact:</b> {_esc(impact)}", st["body"]))
        story.append(Paragraph(f"<b>Tech Stack:</b> <font face='Courier'>{_esc(o.get('tech_stack',''))}</font>", st["body"]))
        if o.get("priority_reasoning"):
            story.append(Paragraph(f"<i>Priority Reasoning: {_esc(o.get('priority_reasoning'))}</i>", st["quote"]))

    # 6. Pitch
    story.append(PageBreak())
    story.append(Paragraph("6. Personalized Pitch to the CEO", st["h1"]))
    for block in pitch.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        if block.startswith("### "):
            story.append(Paragraph(_esc(block.replace("### ", "")), st["h3"]))
        else:
            html = _esc(block).replace("**", "<b>", 1)
            while "**" in html:
                html = html.replace("**", "</b>", 1).replace("**", "<b>", 1)
            story.append(Paragraph(html.replace("\n", "<br/>"), st["body"]))

    # 7. Sources
    story.append(Paragraph("7. Research Sources", st["h1"]))
    if sources:
        from collections import defaultdict
        by_type = defaultdict(list)
        for src in sources:
            by_type[src.get("type", "Other")].append(src)
        for t, srcs in by_type.items():
            story.append(Paragraph(f"<b>{_esc(t)}</b>", st["h2"]))
            story.append(_bullets_pdf(
                [f"{_esc(src.get('title', src.get('url', '')))} — {_esc(src.get('url',''))}" for src in srcs],
                st["body"]
            ))
    else:
        story.append(Paragraph("<i>No URLs captured.</i>", st["body"]))

    story.append(Spacer(1, 14))
    story.append(_hr())
    story.append(Paragraph(
        "<font color='#9ca3af'>Report generated by the AI Research &amp; Recommendation Agent</font>",
        st["subtitle"]))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()
